### ISSUE TITLE
Dependabot auto-merging.

### ISSUE THREAD

**Issue by anthonyshew** [kittrgg/kittr#192]
So I don't have to do it manually!

**Comment by booleans-oss** [comment]
If I understand correctly what you want to do: you want dependabot to merge the update to the develop branch and create a PR to merge to master with the changes ?

If I'm correct, then, dependabot would need to actually merge the updates directly into the develop branch so that Github picks up the recent changes. Unfortunately, Github doesn't support auto-merge (see [#1973](https://github.com/dependabot/dependabot-core/issues/1973)). So to implement this feature, we would need to create a new workflow that would be triggered on every pull request. We verify that it is a PR from dependabot. And then, use a Github Actions to merge the PR automatically.

**Comment by anthonyshew** [comment]
Yup, that's pretty much my idea. I was also considering having a separate branch that collects all dependabot upgrades into one and then PRing those into develop. I do need to put more thought into this one so that I can create something that a) makes sense and b) is easy to use.

**Comment by booleans-oss** [comment]
I think a separate branch would be a lot better (simply to avoid having to pull frequently but also to avoid conflicts). You have Github Actions to help you accomplish that ([dependabot-auto-merge](https://github.com/marketplace/actions/dependabot-auto-merge)). But I don't think it would be possible to automatically create a PR from the dependency branch to the develop. The branch would be ahead compared to the develop branch so you'll have the button to create the PR.

**Comment by anthonyshew** [comment]
I like it!

Let's see if [#211](https://github.com/kittrgg/monorepo/pull/211) is how I'm going to get this handled. Will have to see what happens with new PRs over the next couple days.
